version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: draw_guess_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "draw_guess"
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    command: --wait_timeout=28800 --interactive_timeout=28800 --max_connections=200
volumes:
  db_data: